### PR TITLE
Fix keyboard crash when editing text in widget settings

### PR DESCRIPTION
**Pull request by kevinkoenig**
it turns out that for all other screens the that are derived from Page or TabGroup, etc.  The keyboard is hidden and recreated on every TouchEnd.  For widget settings this is not happening.  So keyboard_base.cpp happily resizes all of the full screen windows.  It finally gets to the MainWindow, and then everything goes bat shit crazy (a technical term).  There are two fixes to this issue.  The first one is in libopenui (e.g. this pull request).  It now protects itself from this situation, by testing if the keyboard is already active.  If it is it takes the appropriate action. 

I will make another fix inside of edgetx so that it duplicates the behavior of every other window, and hides the keyboard on every click.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@kevinkoenig is the fix really meant to encompass all these commits? Or should it be rebased on master?

**Comment by kevinkoenig** [comment]
> @kevinkoenig is the fix really meant to encompass all these commits? Or should it be rebased on master?

It was only meant to encompass the crash fix, but since the original commit was not merged, i think we can merge it at one time.  Your call.  If you want me to revert it, I will.

**Comment by pfeerick** [comment]
lol... we were just talking about that... unless you have objections, 2 for 1 special and PR18 will get the boot. It was a mistake.  :laughing: I've not tested this PR yet, only 18, so will do so now. btw, permission changes are cleanup themselves... those files shouldn't have been executable! 🤦 😆

**Comment by pfeerick** [comment]
Thoughts on merging this @raphaelcoeffic?  I did end up testing this shortly after my prior comment and it was working fine, and fixed the top-bar crash, as well a provided the other functionality that was proposed in PR#18. Then https://github.com/EdgeTX/edgetx/pull/691 can be tweaked and merged.

**Review by raphaelcoeffic — APPROVED** [review]

**Comment by raphaelcoeffic** [comment]
> Thoughts on merging this @raphaelcoeffic? I did end up testing this shortly after my prior comment and it was working fine, and fixed the top-bar crash, as well a provided the other functionality that was proposed in PR#18. Then [EdgeTX/edgetx#691](https://github.com/EdgeTX/edgetx/pull/691) can be tweaked and merged.

It's good for me! Feel free to coordinate the move 🤓

**Pull request merged**
