### PR TITLE
Long Touch functionality and number sign change by long press/touch.

### PR DESCRIPTION
**Pull request by eshifri**
Windows class differentiates short/long touches (1s).
Long touch/press on the number changes the sign (if possible).
This functionality will be used in another edgeTX feature: long press/touch on the switch changes it to !switch.

### CODE REVIEW

**Comment by pfeerick** [comment]
Did I mention I really like this idea... *so* much easier than scrolling for the inverted state... ***AND*** it could be couple with auto switch detection... i.e. I toggle SC, SCup is auto detected, long press SCup and it flips to !SCup, without me having to scroll through the list looking for it... Nice! :)

**Comment by eshifri** [comment]
Thank you! :-)

**Comment by pfeerick** [comment]
Resolves EdgeTX/edgetx/issues/158

**Comment by eshifri** [comment]
No, this is part of EdgeTX/edgetx#435

**Comment by pfeerick** [comment]
Argh! When I saw mention that the other issue couldn't be closed I assumed this had to be the outstanding PR. Yes, cross-repo issue.

**Comment by eshifri** [comment]
Implemented in edgeTX repository EdgeTX/edgeTX#594

**Comment by kevinkoenig** [comment]
So I took a look at the implementation of invert-switch with long-press.  it uses a class called SwitchChoice which reimplements a lot of Choice.  That can be re-implemented to use ChoiceEx, which I just created for the long-press of curves in input and mixer screens.  That would be ideal as then anyone can easily implement long-press on Choice.  

IMHO it is a better long-term approach.  I can then move the implementation of ChoiceEx into libopenui where it belongs. 

The only thing that would need to be done is to add the touch support that is missing in ChoiceEx.  I can do the implementation if people think it is the right thing to do.  LMK

**Comment by eshifri** [comment]
Originally I have implemented long touch functionality in the Windows class also thinking it would be a good idea to have it available for every UI component. Later on I have realized that many classes overwrite onTouchEnd() and it was difficult to trace where it was still available.
Maybe adding ChoiceEx is a better solution. I absolutely agree that long press functionality may be useful in many parts of the system.

**Pull request closed without merging**
