### PR TITLE
Fixed issue #1348

### PR DESCRIPTION
**Pull request by jfrickmann**
Fixes EdgeTX/edgetx/issues/1348

### CODE REVIEW

**Comment by kevinkoenig** [comment]
I took a quick look at this and I believe that this PR will create other issues.  There is definitely an issue with how the LUA widget gets the X coordinates, but I don't believe this is the correct fix.  Stay tuned.

**Comment by jfrickmann** [comment]
I will take your word for that! If this issue is peculiar to Lua widgets in fullscreen mode, then the x-coordinate can also be adjusted here: https://github.com/EdgeTX/edgetx/blob/dc8f86700cc523bc1407f0fd5fd3649ccac4fc60/radio/src/lua/widgets.cpp#L645-L646

**Comment by kevinkoenig** [comment]
It is my belief that this is specific to the full screen lua widget stuff.  I will investigate further

**Comment by kevinkoenig** [comment]
I agree translate the coords just before we call lua.  That is the only safe way to do this

**Comment by jfrickmann** [comment]
OK, I have made another attempt in https://github.com/EdgeTX/edgetx/pull/1409
Closing this PR!

**Pull request closed without merging**
