### PR TITLE
Software keyboard - Fix crash when editing widget settings

### PR DESCRIPTION
**Pull request by kevinkoenig**
Adds focusLost override to NumericKeyboard.  It now hides the keyboard when focus is lost.

### CODE REVIEW

**Comment by pfeerick** [comment]
Specifically, it fixes this sort of problem: 
image
image

Which if you then open the radio menu or look at the transmitter the wrong way, is likely to result in a emergency mode crash

**Comment by raphaelcoeffic** [comment]
@kevinkoenig are the changes in Stb submodule intentional? Could you please get rid of them?

**Comment by pfeerick** [comment]
Go into the `stb` submodule, checkout/reset to commit to `7cce4c3`, and then do a commit to lock that version in. 

Basically the submodule shouldn't have been updated ;).

**Comment by kevinkoenig** [comment]
> Go into the `stb` submodule, checkout/reset to commit to `7cce4c3`, and then do a commit to lock that version in. That should then remove that as being a change made in the PR.
> 
> Basically the `stb` submodule shouldn't have been updated. 😉

I guess you already took care of it.  Thanks.  I will be more careful next time.

**Pull request merged**
