### PR TITLE
minor changes to touch and slide processing.  set event to TE_NONE so…

### PR DESCRIPTION
**Pull request by kevinkoenig**
… you dont continuously get touch end events.

also make sure you get touchEnd if you slid but there is no sliding window (e.g. no scroll happened)

### CODE REVIEW

**Comment by pfeerick** [comment]
Right, so this looks to do what was intended, but in doing so may have removed one aspect I did like with touch... which was that a short brisk swipe could go from one end of list to the other, or from one panel to the next, one end of the carousel to the other, etc. Other than that, it seems to be working perfect AFAICT.

So my question is then this... is this fixing exposing we need something around duration of the touch, i.e. in order to have acceleration? Or am I just being picky (and set in my ways, however wrong they may be)? 😆

**Comment by kevinkoenig** [comment]
> Right, so this looks to do what was intended, but in doing so may have removed one aspect I did like with touch... which was that a short brisk swipe could go from one end of list to the other, or from one panel to the next, one end of the carousel to the other, etc. Now it stops dead when you stop swiping. Other than that, it seems to be working perfect AFAICT.
> 
> So my question is then this... is this exposing we need something around duration of the touch, i.e. in order to have acceleration? Or am I just being picky (and set in my ways, however wrong they may be)? 😆

I am thinking about what I did and how it could have possibly changed that behavior.  Can you better describe what you are seeing.  I just tried it on my radio, and I can swipe from left to right on main menu carosell and get from one end to the other with a  swift swipe.  The other place I tired is in model settings with the multi-module protocol setting.  I can get most of the way from top to bottom with a single swipe.  I will also try it with stock 2.5 dauntless build and see if I can detect any difference.

**Comment by kevinkoenig** [comment]
> Right, so this looks to do what was intended, but in doing so may have removed one aspect I did like with touch... which was that a short brisk swipe could go from one end of list to the other, or from one panel to the next, one end of the carousel to the other, etc. Now it stops dead when you stop swiping. Other than that, it seems to be working perfect AFAICT.
> 
> So my question is then this... is this exposing we need something around duration of the touch, i.e. in order to have acceleration? Or am I just being picky (and set in my ways, however wrong they may be)? 😆

let me check.  I did make a small change that is separate from the other fixes.  I am testing now on radio and I will update you once I learn more

**Comment by kevinkoenig** [comment]
> > Right, so this looks to do what was intended, but in doing so may have removed one aspect I did like with touch... which was that a short brisk swipe could go from one end of list to the other, or from one panel to the next, one end of the carousel to the other, etc. Now it stops dead when you stop swiping. Other than that, it seems to be working perfect AFAICT.
> > So my question is then this... is this exposing we need something around duration of the touch, i.e. in order to have acceleration? Or am I just being picky (and set in my ways, however wrong they may be)? 😆
> 
> let me check. I did make a small change that is separate from the other fixes. I am testing now on radio and I will update you once I learn more

I tracked it down to the two lines below.  If you remove them the slide behaviour reverts back to what is expected.  Everything else I fixed still works AFAICT

[code that needs to be commented](https://github.com/kevinkoenig/libopenui/blob/ea83769efca0528a0241648bd85f91a41e591539/src/mainwindow.cpp#L84-L85
)

**Pull request merged**
