### PR TITLE
Let buttons catch touchStart

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves https://github.com/EdgeTX/edgetx/issues/1087

Thanks @kevinkoenig for the explanation for this ;)

`simu` for TX16S seems a little off on this for the top bar icons in say model setup, but actual hardware seems fine. Will try and look into that a bit further first.

### CODE REVIEW

**Comment by kevinkoenig** [comment]
> Resolves [EdgeTX/edgetx#1087](https://github.com/EdgeTX/edgetx/issues/1087)
> 
> Thanks @kevinkoenig for the explanation for this ;)
> 
> `simu` for TX16S seems a little off on this for the top bar icons in say model setup, but actual hardware seems fine. Will try and look into that a bit further first.

@pfeerick If you look at the implementation of the PageTab() for model settings and hardware settings, it doesnt use buttons for the icons.  It draws images, and does pixel calculations to see which tab is pressed in onTouchEnd().  Therefore i dont see how the change you made here can have any effect on that.  Let me know if you need some additional help.  BTW, when i tried the same fix locally it appears to work perectly.

**Comment by natiho2** [comment]
I also experience this problem, and did not understand what the solution to this

**Comment by pfeerick** [comment]
@natiho2 Please wait for this to be merged. You posted a duplicate issue to one already reported, and once this fix is merged it will be resolved in the next nightly build.

**Comment by pfeerick** [comment]
@kevinkoenig I have absolutely no idea what was going on... another clean build and several commits later on main and it is behaving itself, so `simu` must have been in some weird state. Is working now though

https://user-images.githubusercontent.com/5500713/145202716-b4d5383b-794e-4789-a7fa-990351a65323.mp4

**Pull request merged**
